#!/usr/bin/env node

import fs from 'node:fs';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

export const MERGE_GUARD_COMMENT_MARKER = '<!-- merge-guard-report -->';

function printHelp() {
  console.log(`merge-guard PR comment

Usage:
  node scripts/pr-comment.js --report merge-guard-report.md
  node src/cli.js --markdown pr.diff | node scripts/pr-comment.js

Options:
  --report <path>   Read Markdown report from a file
  --dry-run         Print the comment body without calling GitHub
  --help            Show this help message

Environment:
  GITHUB_TOKEN       Token used to create or update the PR comment
  GITHUB_REPOSITORY  Repository in owner/name form
  GITHUB_EVENT_PATH  GitHub Actions event JSON path
`);
}

function parseArgs(args) {
  const parsed = {
    reportPath: null,
    dryRun: false,
    help: false
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === '--help' || arg === '-h') {
      parsed.help = true;
    } else if (arg === '--dry-run') {
      parsed.dryRun = true;
    } else if (arg === '--report') {
      parsed.reportPath = args[index + 1];
      index += 1;
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }

  if (parsed.reportPath === undefined) {
    throw new Error('--report requires a file path');
  }

  return parsed;
}

function readStdin() {
  return new Promise((resolve, reject) => {
    let data = '';

    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => {
      data += chunk;
    });
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', reject);
  });
}

async function readReport(reportPath) {
  if (reportPath) {
    if (!fs.existsSync(reportPath)) {
      throw new Error(`report file not found: ${reportPath}`);
    }

    return fs.readFileSync(reportPath, 'utf8');
  }

  if (process.stdin.isTTY) {
    throw new Error('no report provided; pass --report <path> or pipe Markdown into stdin');
  }

  return readStdin();
}

function loadEvent(eventPath) {
  if (!eventPath) {
    throw new Error('GITHUB_EVENT_PATH is required outside --dry-run mode');
  }

  if (!fs.existsSync(eventPath)) {
    throw new Error(`GitHub event file not found: ${eventPath}`);
  }

  return JSON.parse(fs.readFileSync(eventPath, 'utf8'));
}

function getPullRequestNumber(event) {
  const number = event?.pull_request?.number || event?.number;

  if (!Number.isInteger(number)) {
    throw new Error('could not find pull request number in GitHub event payload');
  }

  return number;
}

export function buildCommentBody(markdownReport) {
  const report = markdownReport.trim();

  if (!report) {
    throw new Error('report content is empty');
  }

  return `${MERGE_GUARD_COMMENT_MARKER}\n${report}\n\n---\n<sub>Generated by merge-guard. Re-running the workflow updates this comment.</sub>`;
}

export function findMergeGuardComment(comments) {
  return comments.find((comment) => typeof comment.body === 'string' && comment.body.includes(MERGE_GUARD_COMMENT_MARKER)) || null;
}

async function githubRequest({ method, url, token, body }) {
  const response = await fetch(url, {
    method,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'merge-guard'
    },
    body: body ? JSON.stringify(body) : undefined
  });

  if (!response.ok) {
    const responseText = await response.text();
    throw new Error(`GitHub API ${method} ${url} failed with ${response.status}: ${responseText}`);
  }

  if (response.status === 204) return null;
  return response.json();
}

async function listIssueComments({ repository, pullRequestNumber, token }) {
  const comments = [];
  let page = 1;

  while (true) {
    const url = `https://api.github.com/repos/${repository}/issues/${pullRequestNumber}/comments?per_page=100&page=${page}`;
    const pageItems = await githubRequest({ method: 'GET', url, token });

    comments.push(...pageItems);

    if (pageItems.length < 100) break;
    page += 1;
  }

  return comments;
}

async function upsertPullRequestComment({ repository, pullRequestNumber, token, body }) {
  const comments = await listIssueComments({ repository, pullRequestNumber, token });
  const existingComment = findMergeGuardComment(comments);

  if (existingComment) {
    const url = `https://api.github.com/repos/${repository}/issues/comments/${existingComment.id}`;
    await githubRequest({ method: 'PATCH', url, token, body: { body } });
    return { action: 'updated', commentId: existingComment.id };
  }

  const url = `https://api.github.com/repos/${repository}/issues/${pullRequestNumber}/comments`;
  const created = await githubRequest({ method: 'POST', url, token, body: { body } });
  return { action: 'created', commentId: created.id };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    return;
  }

  const report = await readReport(args.reportPath);
  const body = buildCommentBody(report);

  if (args.dryRun) {
    console.log(body);
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;

  if (!token) throw new Error('GITHUB_TOKEN is required outside --dry-run mode');
  if (!repository) throw new Error('GITHUB_REPOSITORY is required outside --dry-run mode');

  const event = loadEvent(process.env.GITHUB_EVENT_PATH);
  const pullRequestNumber = getPullRequestNumber(event);
  const result = await upsertPullRequestComment({ repository, pullRequestNumber, token, body });

  console.log(`merge-guard PR comment ${result.action}: ${result.commentId}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error('merge-guard comment error:', error.message);
    process.exitCode = 1;
  });
}
